
server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: 666666
    url: jdbc:postgresql://localhost:5432/microservice
  jpa:
    open-in-view: 'false'
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always
  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase-changeLog.xml


  jwt:
    exp: 240000
    secret: AB8E50CEE980BC7BD72FB9A49B5262AD01FDF92498FF62C1B9E7E9193CCCCE8E


